version: '3.3'
services:

  qcg-pilotjob:
    restart: unless-stopped
    image: qcg-pilotjob:develop
    volumes:
      - "${REPO_DIR}/qcg:/srv/src/qcg"
      - "${REPO_DIR}/example-scripts:/srv/example-scripts"

